### ISSUE TITLE
loadYaml returns null (3.0.0-nullsafety.0 release)

### ISSUE THREAD

**Issue by hoylen** [dart-lang/yaml#103]
When `loadYaml` is passed the empty string, it returns _null_. For example, if parsing an empty file or a file with only whitespace in it.

But since the return type is `dynamic`, null safety (as implemented by Dart 2.12.0-29.10.beta) doesn't behave as expected. If you check it for null, Dart (incorrectly) tells you the check is unnecessary.

How about returning `Object?` instead?

**Comment by hoylen** [comment]
Dart null safety seems to get confused when `dynamic` is assigned to an `Object`.

```
void main() {
  final Object x = foo(1);
  if (x == null) { // dart null safety strangely thinks this can never be null!
    print('1 was null');
  }

  final y = foo(0);
  if (y == null) { // but this is fine
    print('0 was null');
  }
}

dynamic foo(int p) {
  if (p < 0) {
    return -1;
  } else if (0 < p) {
    return 1;
  } else {
    return null;
  }
}
```

I think I was assigning it to an _Object_ to avoid one of the linter rules about using dynamic.

Maybe _loadYaml_ needs changing or maybe it does not. Up to you.

If there is no change, maybe the documentation for _loadYaml_ can mention that _null_ is returned when there is no YAML content.

**Comment by natebosch** [comment]
The behavior you are seeing is an implicit downcast from `dynamic`. You can detect it statically by opting out of implicit cast from dynamic in your `analysis_options.yaml`

```yaml
analyzer:
  strong-mode:
    implicit-casts: false
```

I agree that `Object?` would be a better return type, given that implicit cast from `dynamic` is still carved out as an allowed foot-gun in the language. I don't know how breaking it would be to change this.

**Comment by natebosch** [comment]
@bwilkerson - it looks like the analyzer relies on implicit casts from dynamic from this call.

**Comment by bwilkerson** [comment]
A quick look leads me to think that we could easily clean up all uses of `loadYaml` so that they either used `loadYamlNode` or at least did an explicit cast.

**Comment by sigurdm** [comment]
Do we want to do anything here?

**Comment by jonasfj** [comment]
I think using `loadYamlNode` is frequently better, but if you want to read YAML the same way you deal with JSON in Dart, then `loadYaml` is probably the right choice, but then you have to be careful about `null`.. It's the same as [`jsonDecode`](https://api.dart.dev/stable/2.14.3/dart-convert/jsonDecode.html) from `dart:convert`.

I think we should close this, as long as `jsonDecode` is using dynamic, then this should probably also use dynamic.
