### ISSUE TITLE
Provision to write map to yaml file

### ISSUE THREAD

**Issue by kalluriramkumar** [dart-lang/yaml#113]
The YAML package supports reading the YAML file. However, at the moment, writing the modified map back YAML file is not supported.

Enhancement request to provide support in writing map to YAML file.

**Comment by KevinBLT** [comment]
Hello,

could you check my implementation and if it fits your need?
https://github.com/dart-lang/yaml/pull/117

I have done some kind of mapping to the JsonCodec features (decode/encode).

There are no formatting options (so far) it just writes a plain yaml as expected to be easy for humans.
One thing: I encountered issues with some special strings, when decoding,
so they are all quoted with single quote by default.

Example usage:  
```dart

const Map test = {
  'string' : 'Test text.',
  'number' : 1337,
  'bool'   : false,
  'list'   : [1,2,3,4],
  'map'    : {
    'a' : 1,
    'b' : 2,
    'c' : 'text',
    'd' : ['a', 'b', 'c']
  }
};

print(yaml.encode(test));

/* Output:
---
string: 'Test text.'
number: 1337
bool: false
list:
  - 1
  - 2
  - 3
  - 4
map:
  a: 1
  b: 2
  c: 'text'
  d:
    - 'a'
    - 'b'
    - 'c'
*/
```

**Comment by jonasfj** [comment]
For writing and modifying YAML, see [package:yaml_edit](https://pub.dev/packages/yaml_edit).

You can use it to write YAML by creating an empty document and updating it.

-----

I'm not sure we should add it here, but perhaps we should give the package `README` a reference to `yaml_edit` for people who want to discover such features.
