### ISSUE TITLE
Dartium showing this error 2.1.7

### ISSUE THREAD

**Issue by irfman12** [dart-lang/yaml#17]
` Internal error: 'package:yaml/src/loader.dart': error: line 197 pos 32: unexpected token '?'
      _tryParseScalar(scalar) ?? new YamlScalar.internal(scalar.value, scalar);`

I'm not sure if it's a bug or not, but I can't figure out what's causing this

using dart pub 1.12.1

**Comment by zoechi** [comment]
The package does have the right SDK constraint. What Dart version are you using?   
See also http://stackoverflow.com/questions/33173199/dartium-chromium-error-on-yaml-src-loader-dart

**Comment by nex3** [comment]
You need to make sure you're using a version of Dartium whose Dart VM is compatible with the version of `yaml` you're using. `yaml` 2.1.7 requires at least version `1.12.0` of Dart, for reference.

Unfortunately, there's not a great way of constraining Dartium versions. Dartium isn't installed with the Dart SDK so there's no way to guarantee that it has the same version as the SDK, which means that you as a user need to be extra vigilant about ensuring that it's up-to-date.
