### ISSUE TITLE
Dumping?

### ISSUE THREAD

**Issue by trans** [dart-lang/yaml#23]
Any idea when dumping might be supported?

**Comment by nex3** [comment]
Duplicate of #2.

I personally have no plans to work on this anytime soon. Note that `JSON.encode()` will produce valid YAML output, although it won't be pretty.

**Comment by trans** [comment]
`JSON.encode` can only produce a subset of YAML. No tag support for example.

**Comment by nex3** [comment]
That's true. This package doesn't provide much flexibility for working with tags in general, though, so even if it supported emitting YAML it may not immediately support tagging it.
