### ISSUE TITLE
YamlMap should maintain order

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/yaml#25]
I see that the implementation uses Hashmap.

For speed, I get it. But I'd argue that preserving order would be a good feature to add.

...or at least document that it's not.

**Comment by nex3** [comment]
This is explicitly forbidden by [the YAML spec](http://yaml.org/spec/1.2/spec.html#id2763035), which says

> Construction [of native data structures] must be based only on the information available in the representation, and not on additional serialization or presentation details such as [...] mapping key order

Since it's documented frequently and clearly in the format documentation itself, I don't think it's necessary to document in the library—we generally avoid duplicating format information.

**Comment by kevmoo** [comment]
Got it
