### ISSUE TITLE
An unwrap mechanism?

### ISSUE THREAD

**Issue by xster** [dart-lang/yaml#26]
Context: read some yaml file then process it programmatically before passing on the map

But it's not easy to turn a YamlMap into a mutable form. The mutable scenario should be fairly common. Could there be a converter for YamlMaps to normal dart maps?

**Comment by nex3** [comment]
I think what you're looking for is a `deepCopy()` function that takes a JSON-like object and returns a (mutable) copy of it. I don't know of any standard implementation of that, but it should only be a few lines to implement it yourself.

I think this is outside the scope of this package, but feel free to file a feature request against [`collection`](https://github.com/dart-lang/collection) to add `deepCopy()`.
