### ISSUE TITLE
YamlList needs to take type parameters?

### ISSUE THREAD

**Issue by eseidel** [dart-lang/yaml#36]
I'm attempting to make some of my code strong-mode clean.

For example:
```dart
    YamlList yamlItems = yamlMob['items'];
    if (yamlItems != null) {
      yamlItems.forEach(
          (String itemName) => mob.addItem(creator.items.itemByName(itemName)));
    }
```

Complains:
```
file: 'file:///Stuff/Projects/lol_duel/lib/utils/duel.dart'
severity: 'Info'
message: 'A function of type '(String) → Item' can't be assigned to a variable of type '(dynamic) → void'.'
at: '46,11'
source: 'dart'
code: 'uses_dynamic_as_bottom'
```

If this were a normal list, I'd fix it by using:
`List<String> items`

But I can't do that for YamlList, even thought it implements ListMixin which takes a type parameter:
`abstract class ListMixin<E> implements List<E> {`

**Comment by eseidel** [comment]
I worked around this by using List<T> directly, since that's theoretically a superclass of YamlList?
https://github.com/eseidel/lolsim/commit/2733e13b7ee4f93a0adb0f766afde7e340b325e3
Not sure if that was the correct approach or if this will apply to others.

(This is not important, just me doing some fun hacking over the holidays.)

**Comment by nex3** [comment]
This warning is correct—there's no guarantee that the elements of `yamlItems` are strings, so the callback you're passing may not be valid. I'd rewrite this as:

```dart
var yamlItems = yamlMob['items'];
if (yamlItems != null) {
  yamlItems.forEach(
      (itemName) => mob.addItem(creator.items.itemByName(itemName as String)));
}
```

**Comment by eseidel** [comment]
(Before your reply) I ended up writing it as:
```dart
    List<String> yamlItems = yamlMob['items'];
    if (yamlItems != null) {
      yamlItems.forEach(
          (String itemName) => mob.addItem(creator.items.itemByName(itemName)));
    }
```
I'm not sure if that's better or worse, but it seems to compile and run with the default options in at least the latest dart 2.0 devel brew release.

**Comment by eseidel** [comment]
Nm, I had already written that above, my bad.
