### ISSUE TITLE
Spans aren't correct for list nodes with a null value

### ISSUE THREAD

**Issue by jakemac53** [dart-lang/yaml#49]
Repro program:

```
import 'package:yaml/yaml.dart';

main() {
  var yaml = loadYaml('''
- foo
- 
- bar
''');

  print(yaml.nodes.firstWhere((n) => n.value == null).span.highlight());
}
```

Prints:

```
- bar
 ^
```

Where I would expect something like:

```
- 
^
```

**Comment by adarsh-maurya2699** [comment]
Hi @jakemac53, I have some doubts regarding purpose of the nested "if block", I may be wrong but if it is meant to add empty scalar node when there is a null node in block sequence, then it maybe passing the next node's token information to the create the scalar node.

`
  Event _parseBlockSequenceEntry() {
    
    var token = _scanner.peek();
    if (token.type == TokenType.blockEntry) {
      token = _scanner.advance();

      if (token.type == TokenType.blockEntry ||               //
          token.type == TokenType.blockEnd) {                 // This if block
        _state = _State.BLOCK_SEQUENCE_ENTRY;                 //
        return _processEmptyScalar(token.span.end);           //
      } else {
        _states.add(_State.BLOCK_SEQUENCE_ENTRY);
        return _parseNode(block: true);
      }
    }

    if (token.type == TokenType.blockEnd) {
      _scanner.scan();
      _state = _states.removeLast();
      return Event(EventType.sequenceEnd, token.span);
    }

    throw YamlException("While parsing a block collection, expected '-'.",
        token.span.start.pointSpan());
  }
`
The value of token before scanner advances could be more appropriate perhaps ?
