### ISSUE TITLE
Order of map is nondeterministic, making read+write randomize the file

### ISSUE THREAD

**Issue by rakudrama** [dart-lang/yaml#55]
The use of a HashMap here https://github.com/dart-lang/yaml/blob/master/lib/src/equality.dart#L13
ensures that when the elements of a map are added here https://github.com/dart-lang/yaml/blob/master/lib/src/loader.dart#L156
the order is nondeterministic.

This shows itself in tools that read then write yaml - the output is needlessly reorganized.

The default behaviour should keep the input order (change HashMap to LinkedHashMap)

Sorting would be a nice option, but keeping the original order would

**Comment by shyndman** [comment]
Hello yaml maintainers,

Would you consider accepting a pull for this? Do you anticipate much breakage downstream if it's fixed?

**Comment by shyndman** [comment]
Ping @rakudrama

**Comment by 2dxgujun** [comment]
+1 Same problem here

**Comment by rakudrama** [comment]
+ @vsmenon could we find an owner for this issue?
