### ISSUE TITLE
Build fails due to bug in dependency 'source_span v1.5.5'

### ISSUE THREAD

**Issue by adarshm-26** [dart-lang/yaml#81]
The source_span v1.5.5 had a [bug](https://pub.dev/packages/source_span#156) where the span for line numbers multiple of 10 had less padding than others. Here, travis jobs with dart-sdk 2.4.0 fetch version 1.5.5 during `pub get` and for these jobs the _expectSpan() method fails from incorrect span information. The build that failed is [here](https://travis-ci.org/github/dart-lang/yaml/builds/677661080).
Reproduction program -
```dart
import 'package:source_span/source_span.dart';
void main() {
  const dtr = r'''
1
2
3
4
5
6
7
8
9
10
11
''';
  var fs = SourceFile.fromString(dtr);
  var offset = fs.getOffset(8);
  var span = fs.location(offset).pointSpan();
  print(span.message('padding of 1 space')); 

  offset = fs.getOffset(9);
  span = fs.location(offset).pointSpan();
  print(span.message('padding of 0 space'));

  offset = fs.getOffset(10);
  span = fs.location(offset).pointSpan();
  print(span.message('padding of 1 space'));
}
```
Output (using source_span: '1.5.5')-
```console
line 9, column 1: padding of 1 space
  ╷
9 │ 9
  │ ^
  ╵
line 10, column 1: padding of 0 space
  ╷
10│ 10
  │ ^
  ╵
line 11, column 1: padding of 1 space
   ╷
11 │ 11
   │ ^
   ╵
```

**Comment by sigurdm** [comment]
Is this still relevant?
