### ISSUE TITLE
Change String or Uri arguments to Uri

### ISSUE THREAD

**Issue by natebosch** [dart-lang/yaml#97]
Adding a static type makes the API easier to use correctly. The call site can easily inline the `Uri.parse` if necessary.

**Comment by kevmoo** [comment]
Why not `Object?` – this is going to be annoying to deal with.

We didn't make the same update to `SpanScanner.eager` in `StringScanner`

**Comment by kevmoo** [comment]
I wish we had https://github.com/dart-lang/language/blob/master/working/0107%20-%20implicit-constructors/feature-brainstorm.md#syntax

**Comment by natebosch** [comment]
> Why not `Object?`

Because that doesn't add any safety. It doesn't stop me from sending in a `File` or something weird.



> this is going to be annoying to deal with.

This is the direction we are moving with all arguments that unnecessarily are `dynamic` or `Object` to allow either `String` or `Uri`. Why do you think it will be annoying?

In _all_ internal uses of this package, there was only a single library that I found was impacted. I did not scan on pub, but I don't expect there to be much impact.

The fix is also straightforward. https://dart-review.googlesource.com/c/sdk/+/171440

> We didn't make the same update to `SpanScanner.eager` in `StringScanner`

We will. https://github.com/dart-lang/string_scanner/issues/30

**Comment by kevmoo** [comment]
ack...alright.
